### ISSUE TITLE
small issue

### ISSUE THREAD

**Issue by byteslaves** [engapplabs/flutter_websocket_plugin#5]
Hello, I'm glad to use the plugin you developed，This solved my big problem. 
Thank you very much for your selfless dedication.
In use, I found a small problem. When using the client to send a heartbeat and the server to return a heartbeat, it always outputs a Received message on the command line: ******, I think this is unnecessary data, which will affect For other code debugging, you can consider whether to use print in the code I write.

   void _messageListener (dynamic message) {
     print ('Received message: $ message'); // this line
     if (_messageCallback! = null) {
       _messageCallback (message);
     }
   }

**Comment by luanhssa** [comment]
Thanks for your comment! I'm glad this plugin worked for you!

We've fixed this problem on version 0.2.1 (updated today)
